const Airport = require('./Airport')
const Plane = require('./Plane')
const Passenger = require('./Passenger')

describe('Airport', function(){
    // test('How many planes in London', function(){
    //     airport = new Airport('London')
    //     let plane = new Plane('London')
    //     plane = new Plane('Glasgow')
    //     plane = new Plane('Dublin')
    //     airport.addPlane('London')
    //     airport.addPlane('Glasgow')
    //     airport.addPlane('Dublin')
    //     expect(airport.planes.length).toBe(3)
    //     expect(airport.planes[0]).toBe('London')
    // })
    test('London to Glasgow', ()=>{
        airport1 = new Airport('London')
        airport2 = new Airport('Glasgow')
        plane = new Plane()
        plane.setDestination(airport2.name)
        airport1.addPlane(plane)
        expect(plane.location).toEqual('London')
        expect(plane.destination).toEqual('Glasgow')
        airport1.takeoff(plane)
        expect(airport1.planes.length).toBe(0)
        expect(airport2.planes.length).toBe(1)
        expect(plane.location).toEqual('Glasgow')
    })
})